language: node_js
env:
  global:
    # codeclimate test reporter
    - CC_TEST_REPORTER_ID=e8e73e402ea1c4e5bed648c40d89b91413c1c05842c1419447aa09a31bfa2c8e
matrix:
  include:
  - node_js: '10'
  - node_js: '12'
cache:
  directories: node_modules
after_success: yarn uploadCoverage
script:
  - yarn test
# codeclimate config
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
